Test commit

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,1 +1,16 @@
-prettier $(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g') --write --ignore-unknown
+#!/bin/sh
+. "$(dirname "$0")/_/husky.sh"
+
+# Check for changes in the backend folder with specific file extensions
+changed_files=$(git diff --cached --name-only | grep -E '^apps/backend/.*\.(js|ts|jsx|tsx)$')
+
+if [ -n "$changed_files" ]; then
+  echo "Detected changes in backend files. Running yarn build:backend..."
+  yarn build:backend
+  if [ $? -ne 0 ]; then
+    echo "Build failed. Commit aborted."
+    exit 1
+  fi
+else
+  echo "No relevant changes detected. Skipping build."
+fi
